# Generated by Django 5.2.4 on 2025-07-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('date_of_hire', models.DateField()),
                ('employment_type', models.CharField(choices=[('Full time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('active_status', models.BooleanField()),
            ],
        ),
    ]
